version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build Angular app
      - npm run build -- --configuration production
artifacts:
  files:
    - '**/*'
  base-directory: dist/ccms
